- name: configure logging source command
  connection: network_cli
  gather_facts: no
  hosts: switch

  tasks:

  - name: "Get interface list"  
    ios_command: 
      commands:  
        - "show ip interface brief | inc \\.[0-9]+[ ]+YES"  
    register: printout

  - set_fact:  
       svi: |  
         {{printout.stdout_lines[0] |   
           map('regex_findall','^([A-Za-z]+[0-9./]+)') |   
           map('join') | list }}